### ISSUE TITLE
In case of sbt, waiting for sbt download each time

### ISSUE THREAD

**Issue by dragoslav** [magneticio/buildserver#2] opened 2017-01-19 19:04 UTC
Vamp project:
```
$ make
docker run \
	        --name buildserver \
		--interactive \
		--rm \
		--volume /Users/dragoslav/workspace/vamp:/srv/src \
		--volume /Users/dragoslav/.sbt:/home/vamp/.sbt \
		--volume /Users/dragoslav/.ivy2:/home/vamp/.ivy2 \
		--workdir=/srv/src \
		--env BUILD_UID=501 \
		--env BUILD_GID=20 \
		magneticio/buildserver \
			make clean test build
sbt clean
Getting org.scala-sbt sbt 0.13.13 ...
```

`sbt` should be already available without downloading it every time: http://stackoverflow.com/questions/27031262/why-does-sbt-want-to-get-org-scala-sbt-while-it-has-already-been-installed

**Comment by iamtew** [comment] 2017-02-23 10:39
Can't reproduce with Docker for Mac, closing.

Save as #4

**Closed by iamtew** 2017-02-23 10:39 UTC
Labels: bug
